runtime:
  model_provider: gradient
  model_name: openai-gpt-oss-120b
  temperature: 0.6

workflow:
  start: supervisor_agent
  end: supervisor_agent
  edges:
    - [data_cleaning_agent, feature_analysis_agent]
    - [feature_analysis_agent, visualization_agent]
    - [visualization_agent, insight_generation_agent]
    - [insight_generation_agent, recommendation_agent]


agents: []
